# Generated by Django 2.2.1 on 2019-05-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom du jeu', max_length=300, unique=True)),
                ('description', models.TextField(help_text='description du jeu')),
                ('date', models.DateTimeField()),
                ('tarif', models.FloatField()),
                ('playersmin', models.IntegerField(help_text='Nombre de joueurs minimum')),
                ('playersmax', models.IntegerField(help_text='Nombre de joueurs maximum')),
                ('timemin', models.IntegerField(help_text='temps de jeu minimum')),
                ('timemax', models.IntegerField(help_text='temps de jeu maximum')),
                ('agemin', models.IntegerField(help_text='age minimum')),
                ('extension', models.BooleanField(default=False, help_text="Est ce que ce jeu est une extension d'un autre?")),
                ('creators', models.ManyToManyField(help_text='createurs du jeu', related_name='creators', to='common.Person')),
                ('genres', models.ManyToManyField(help_text='genres du jeu', to='common.Genre')),
                ('localisation', models.ForeignKey(help_text='lieu où est le film', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Localisation')),
            ],
        ),
    ]
