# Generated by Django 2.2.1 on 2019-05-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du format', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Rapide description du format', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du format', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du film', max_length=300)),
                ('synopsis', models.TextField(help_text='synopsis du film')),
                ('date', models.DateTimeField()),
                ('actors', models.ManyToManyField(help_text='acteurs principaux du film', related_name='actors', to='common.Person')),
                ('format', models.ForeignKey(help_text='format du film', on_delete=django.db.models.deletion.DO_NOTHING, to='film.Format')),
                ('genres', models.ManyToManyField(help_text='genres du film', to='common.Genre')),
                ('langue', models.ForeignKey(help_text='langue.s du film', on_delete=django.db.models.deletion.DO_NOTHING, to='film.Langue')),
                ('localisation', models.ForeignKey(help_text='lieu où est le film', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Localisation')),
                ('realisators', models.ManyToManyField(help_text='realisateurs du film', related_name='realisators', to='common.Person')),
            ],
            options={
                'unique_together': {('title', 'format', 'langue')},
            },
        ),
    ]
