# Generated by Django 2.2.1 on 2019-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='french_title',
            field=models.CharField(default='test', help_text='Titre du film français', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Titre du film original', max_length=300),
        ),
    ]
