# Generated by Django 2.2.1 on 2019-05-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20190525_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(blank=True, help_text='format du film', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='film.Format'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='langue',
            field=models.ForeignKey(blank=True, help_text='langue.s du film', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='film.Langue'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='localisation',
            field=models.ForeignKey(blank=True, help_text='lieu où est le film', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Localisation'),
        ),
    ]
