# Generated by Django 2.2.1 on 2019-05-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20190525_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(default=1, help_text='format du film', on_delete=django.db.models.deletion.DO_NOTHING, to='film.Format'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='langue',
            field=models.ForeignKey(default=1, help_text='langue.s du film', on_delete=django.db.models.deletion.DO_NOTHING, to='film.Langue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='localisation',
            field=models.ForeignKey(default=1, help_text='lieu où est le film', on_delete=django.db.models.deletion.DO_NOTHING, to='common.Localisation'),
            preserve_default=False,
        ),
    ]
