# Generated by Django 2.2.1 on 2019-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20190525_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.CharField(choices=[('Tous Publics', 'Tous Publics'), ('Tous Publics (avec avertissement)', 'Tous Publics (avec avertissement)'), ('plus de 10ans', 'plus de 10ans'), ('plus de 12ans', 'plus de 12ans'), ('plus de 16ans', 'plus de 16ans'), ('plus de 18ans', 'plus de 18ans'), ('Adult', 'Adult')], default='plus de 12ans', help_text='certification', max_length=50),
            preserve_default=False,
        ),
    ]
