# Generated by Django 2.2.1 on 2019-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_movie_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(choices=[('Tous Publics', 'Tous Publics'), ('Tous Publics (avec avertissement)', 'Tous Publics (avec avertissement)'), ('plus de 10ans', '10'), ('plus de 12ans', '12'), ('plus de 16ans', '16'), ('plus de 18ans', '18'), ('Adult', 'X')], help_text='certification', max_length=50),
        ),
    ]
