# Generated by Django 2.2.1 on 2019-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20190529_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(choices=[('tous publics', 'Tous public'), ('tous publics (avec avertissement)', 'Tous publics (avec avertissement)'), ('10', 'plus de 10ans'), ('12', 'plus de 12ans'), ('16', 'plus de 16ans'), ('18', 'plus de 18ans'), ('X', 'Adulte')], help_text='certification', max_length=50),
        ),
    ]
